[package]
name = "kruma"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.7"
libc = "0.2"
cfg-if = "1.0"
wide = "0.7"

[target.'cfg(target_os = "macos")'.dependencies]
metal = "0.32.0"
core-graphics = "0.24.0" 

[build-dependencies]
cc = "1.0"